# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://manikyabard.github.io/metrics-anomaly/"

git_url = "https://github.com/manikyabard/metrics-anomaly/tree/master/"

def custom_doc_links(name): return None
